name = "discord-random-defense-api"
main = "src/index.ts"
compatibility_date = "2026-06-03"

[[d1_databases]]
binding = "DB"
database_name = "discord_random_defense"
database_id = "0fdde997-1f97-4693-a15d-4c69d488a4d4"

[vars]
PUBLIC_APP_URL = "http://localhost:5173"
DISCORD_REDIRECT_URI = "http://localhost:8787/api/auth/callback"
